# Generated by Django 5.1.1 on 2026-04-01 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otp_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 1, 21, 46, 23, 285203, tzinfo=datetime.timezone.utc)),
        ),
    ]
