# Generated by Django 5.1.1 on 2026-04-01 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 1, 21, 57, 25, 856268, tzinfo=datetime.timezone.utc)),
        ),
    ]
