# Generated by Django 6.0.3 on 2026-04-11 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 11, 10, 19, 22, 280439, tzinfo=datetime.timezone.utc)),
        ),
    ]
