# Generated by Django 6.0.3 on 2026-04-11 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 11, 22, 43, 49, 500007, tzinfo=datetime.timezone.utc)),
        ),
    ]
