# Generated by Django 6.0.3 on 2026-04-16 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 16, 16, 1, 4, 594644, tzinfo=datetime.timezone.utc)),
        ),
    ]
