# Generated by Django 6.0.3 on 2026-04-16 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 16, 18, 55, 15, 856804, tzinfo=datetime.timezone.utc)),
        ),
    ]
