# Generated by Django 6.0.3 on 2026-04-20 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 20, 12, 16, 35, 765048, tzinfo=datetime.timezone.utc)),
        ),
    ]
