# Generated by Django 6.0.3 on 2026-05-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_reset_password',
            field=models.BooleanField(default=False),
        ),
    ]
