# Generated by Django 6.0.3 on 2026-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('doctors', '0012_subspecialization_question_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='specialization',
        ),
        migrations.AddField(
            model_name='article',
            name='specialization',
            field=models.ManyToManyField(blank=True, null=True, to='doctors.subspecialization'),
        ),
    ]
