# Generated by Django 6.0.3 on 2026-05-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_specialization_article_specialization'),
        ('doctors', '0012_subspecialization_question_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='specialization',
        ),
        migrations.AddField(
            model_name='article',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doctors.subspecialization'),
        ),
    ]
