# Generated by Django 5.1.1 on 2026-03-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='question_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assessments.questiongroup'),
        ),
    ]
