# Generated by Django 5.1.1 on 2026-03-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_useranswer_question_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroption',
            name='question',
        ),
    ]
