# Generated by Django 6.0.3 on 2026-06-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_appointment_type_appointment_type'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='patient',
        ),
        migrations.AddField(
            model_name='rating',
            name='appointment',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
