# Generated by Django 6.0.3 on 2026-06-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_remove_rating_doctor_remove_rating_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
