# Generated by Django 6.0.3 on 2026-05-22 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingExerciseEntity',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('boxBreathing', 'Box Breathing'), ('fourSevenEight', '4-7-8 Breathing'), ('diaphragmatic', 'Diaphragmatic Breathing'), ('pacedBreathing', 'Paced Breathing'), ('resonance', 'Resonance Breathing')], max_length=50)),
                ('duration_minutes', models.IntegerField()),
                ('inhale_seconds', models.IntegerField()),
                ('hold_seconds', models.IntegerField()),
                ('exhale_seconds', models.IntegerField()),
                ('rest_seconds', models.IntegerField()),
                ('steps', models.JSONField(help_text='Ordered list of string steps')),
                ('recommended_for', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MusicEntity',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_url', models.URLField()),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('source_type', models.CharField(choices=[('bensound', 'Bensound'), ('freemusicarchive', 'Free Music Archive'), ('pixabay', 'Pixabay'), ('incompetech', 'Incompetech'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('supported_feelings', models.JSONField(help_text='List of FeelingType strings')),
                ('therapeutic_goals', models.JSONField(help_text='List of MusicTherapeuticGoal strings')),
                ('is_instrumental', models.BooleanField(default=True)),
                ('duration_seconds', models.IntegerField()),
                ('tempo_bpm', models.IntegerField()),
                ('novelty_score', models.IntegerField(default=5)),
                ('license_text', models.TextField()),
                ('attribution_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_selected_feeling', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('anxious', 'Anxious')], max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relax_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
