# Generated by Django 6.0.3 on 2026-04-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_appointment_type_payment_sessionprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionprice',
            old_name='Doctor',
            new_name='doctor',
        ),
    ]
