# Generated by Django 6.0.3 on 2026-06-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rename_doctor_sessionprice_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_type',
            new_name='type',
        ),
    ]
