# Generated by Django 6.0.3 on 2026-06-08 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_cancelled_by_payment_viewed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='viewed_by',
        ),
        migrations.AddField(
            model_name='payment',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
