# Generated by Django 5.2.7 on 2026-06-08 20:33

from django.db import migrations, models


def set_session_price_duration_to_30(apps, schema_editor):
    SessionPrice = apps.get_model('appointments', 'SessionPrice')
    SessionPrice.objects.update(duration=30)


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_remove_payment_viewed_by_payment_viewed_by'),
        ('doctors', '0013_doctor_photo'),
    ]

    operations = [
        migrations.RunPython(
            set_session_price_duration_to_30,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='sessionprice',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddConstraint(
            model_name='sessionprice',
            constraint=models.UniqueConstraint(fields=('doctor', 'type'), name='unique_doctor_session_type'),
        ),
    ]
