# Generated by Django 6.0.3 on 2026-04-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
