# Generated by Django 5.1.1 on 2026-03-25 09:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctorschedule_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DoctorEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('brief_description', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='doctors.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MainSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_specialization', to='doctors.doctor')),
                ('specialization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_specialization', to='doctors.doctorspecialties')),
            ],
        ),
        migrations.DeleteModel(
            name='DoctorDomain',
        ),
    ]
