# Generated by Django 5.1.1 on 2026-03-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorschedule_created_at_doctorschedule_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='rating',
        ),
    ]
