# Generated by Django 5.1.1 on 2026-04-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_doctor_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='DoctorEducation',
            new_name='Education',
        ),
        migrations.RenameModel(
            old_name='DoctorPaymentMethod',
            new_name='PaymentMethod',
        ),
        migrations.RenameModel(
            old_name='DoctorSchedule',
            new_name='Schedule',
        ),
        migrations.RenameModel(
            old_name='DoctorSpecialties',
            new_name='Specialties',
        ),
        migrations.AddField(
            model_name='doctor',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.job_title'),
        ),
        migrations.DeleteModel(
            name='MainSpecialization',
        ),
    ]
