# Generated by Django 6.0.3 on 2026-04-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_education_created_at_education_reveiwed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='media/certificates/%Y/%m/%d/'),
        ),
    ]
