# Generated by Django 6.0.3 on 2026-04-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_alter_education_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='subspecializations',
            field=models.ManyToManyField(to='doctors.subspecialization'),
        ),
    ]
