# Generated by Django 6.0.3 on 2026-04-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_subspecialization_doctor_subspecializations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='subspecializations',
            new_name='specialties',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
    ]
