# Generated by Django 6.0.3 on 2026-04-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_rename_subspecializations_doctor_specialties_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialties',
        ),
    ]
