# Generated by Django 6.0.3 on 2026-05-09 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('doctors', '0011_delete_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='subspecialization',
            name='question_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subspecializations', to='assessments.questiongroup'),
        ),
        migrations.AlterField(
            model_name='subspecialization',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
