# Generated by Django 6.0.3 on 2026-06-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_subspecialization_question_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/doctor_photos/%Y/%m/%d/'),
        ),
    ]
